repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  # Dev Portal checks
  - repo: local
    hooks:
      - id: format check
        name: running dev portal format check
        language: system
        entry: sh -c "cd frontend && npm run format"
        pass_filenames: false
        require_serial: true
      - id: lint check
        name: running dev portal lint check
        language: system
        entry: sh -c "cd frontend && npm run lint"
        pass_filenames: false
        require_serial: true
      - id: test check
        name: running dev portal test check
        language: system
        entry: sh -c "cd frontend && npm run test:run"
        pass_filenames: false
        require_serial: true
