FROM python:3.12

WORKDIR /workdir

COPY ./requirements.txt /workdir/

RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

ENV PYTHONPATH=/workdir

# RUN playwright install chromium --with-deps --no-shell